### ISSUE TITLE
forked ^_^

### ISSUE THREAD

**Issue by kviccn** [hacking-with-angular/hacking-with-angular.github.io#1]
谢谢老师，今早坐公交车的时候在开发者头条上看到依赖注入这篇文章，感觉写的不错，下午就fork了跟着练。正好前几天跟着官网的例子敲了一遍，所以很上手。老师能不能写一些实战的教程，还想请问老师如何学以致用。^_^

**Comment by dreamapplehappy** [comment]
@kviccn 过奖了，老师称不上，不好意才看到你的留言；很感谢你的支持，我写这些的初衷就是为了能够帮助大家更好地上手`angular2`;后期我会继续写一些实战类的教程的，我打算把这个`hacking-with-angular`继续做下去，让大家都可以在这里学习到一些东西。关于学以致用，拿`angular2`来举例的话，那就是使用它来重写你原来使用别的框架或者库完成的东西；当然前提是你要把这些都学好了；最后还是谢谢你的支持啦
